# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire Next.js project to the working directory
COPY . .

# Build the Next.js app
RUN npm run build

# Expose the port on which the Next.js app will run (default is 3000)
EXPOSE 3000

# Start the Next.js app
CMD ["npm", "start"]
